<a href="https://colab.research.google.com/github/hkk0x26/hkk0x26.github.io/blob/master/Tensorflow_for_Engineers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install tensorflow==2.0rc

     |████████████████████████████████| 86.3MB 26kB/s 
     |████████████████████████████████| 4.3MB 45.1MB/s 
     |████████████████████████████████| 501kB 51.3MB/s 
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [0]:
import tensorflow as tf
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt


In [3]:
tf.__version__

'2.0.0-rc0'

### Introduction to Tensor

In mathematics, a tensor is an algebraic object that describes a linear mapping from one set of algebraic objects to another.


In [7]:
tensor_0d = tf.constant(3.0,dtype='float32')
print(tensor_0d) ## constant, zero degree tensor

tf.Tensor(3.0, shape=(), dtype=float32)


In [9]:
tensor_1d = tf.constant([1,2,3])
print(tensor_1d) ## Vector, one degree tensor

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [11]:
tensor_2d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_2d)## Matrix, two degree tensor

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
